#!/bin/sh
#ddev-generated

## Description: Run the config_inspector module to check for invalid configuration in the site.
## Usage: config-inspector
## Example: ddev config-inspector

# Check if the config_inspector module is enabled
if ! drush pm:list --type=module --status=enabled | grep -q "config_inspector"; then
  echo "The config_inspector module is not enabled. Please enable it first."
  echo "Run 'ddev drush en config_inspector' to enable the module."
  exit 1
fi

if [ -f "${DDEV_COMPOSER_ROOT}"/config_inspector-baseline.json ]; then
  echo "Using baseline file: ${DDEV_COMPOSER_ROOT}/config_inspector-baseline.json"
  drush config:inspect --baseline="${DDEV_COMPOSER_ROOT}"/config_inspector-baseline.json --only-error --detail
else
  drush config:inspect --only-error --detail
fi
